AWSTemplateFormatVersion: 2010-09-09

Description: Create Nat Gateway in each public subnets

Parameters:
  VpcStackName:
     Description: Name of the VPC stack to export value from
     Type: String

Resources:
   NatGatewayAEIP:
      Type: AWS::EC2::EIP
      Properties:
        Domain: VPC
        Tags: 
          - Key: Name
            Value: EIP A

   NatGatewayA:
      Type: AWS::EC2::NatGateway
      Properties:
        AllocationId: !GetAtt NatGatewayAEIP.AllocationId
        SubnetId:
          Fn::ImportValue: !Sub ${VpcStackName}-PublicSubnetA
        Tags: 
          - Key: Name
            Value: NatGateway public sabnet A 

   PrivateRouteTableA:
      Type: AWS::EC2::RouteTable
      Properties:
         Tags:
           - Key: Name
             Value: Private route table A
         VpcId:
           Fn::ImportValue: !Sub ${VpcStackName}-VPC

   PrivateRouteA:
      Type: AWS::EC2::Route
      Properties:
         DestinationCidrBlock: 0.0.0.0/0
         NatGatewayId: !Ref NatGatewayA
         RouteTableId: !Ref PrivateRouteTableA

   PrivateSubnetARouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref PrivateRouteTableA
        SubnetId:
          Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetA