AWSTemplateFormatVersion: 2010-09-09

Description: Create RDS Database using MYSQL V 5.7

Metadata:
  AWS::CloudFormation::Interface:
     ParameterGroup:
       - 
         Label:
           default: Export VPC stack name
         Parameters:
           - ExportVpcStackName
       -
         Label:
           default: Database Parameters
         Parameters:
           - DatabaseInstanceIdentifier
           - DatabaseName
           - DatabaseUser
           - DatabasePassword
           - DatabaseBackupRetentionPeriod
           - DatabaseAllocatedStorage
           - DatabaseInstanceClass
           - MultiAZDatabase

Parameters:
   ExportVpcStackName:
      Description: vpc that exports the values
      Type: String
      Default: vpc

   DatabaseInstanceIdentifier:
      AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
      ConstraintDescription: Must begin with leters and can be alphanumeric
      Default: mysqldb
      Description: Instance identifier name
      MaxLength: 60
      MinLength: 1
      Type: String

   DatabaseName:
      AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
      ConstraintDescription: Must begin with leters and can be alphanumeric
      Default: appdb
      Description: MYSQL database
      MaxLength: 64
      MinLength: 1
      Type: String  

   DatabaseUser:
      AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
      ConstraintDescription: Master username
      Default: appdbadmin
      Description: Username for MYSQL access
      MaxLength: 16
      MinLength: 1
      NoEcho: true
      Type: String 

   DatabasePassword:
      AllowedPattern: '[a-zA-Z0-9]*'
      ConstraintDescription: Database password alphanumeric 
      Default: testPass12
      Description: MYSQL database access password
      MaxLength: 41
      MinLength: 8
      NoEcho: true
      Type: String 

   DatabaseBackupRetentionPeriod:
      ConstraintDescription: Database backup rentention period 0-35 days
      Default: 0 
      Description: days between backup; 0 - no backup
      MaxValue: 35
      MinValue: 0
      Type: Number

   DatabaseAllocatedStorage:
      ConstraintDescription: Must be between 5 and 1024 Gb
      Default: 20
      Description: Database size in Gb
      MaxValue: 1024
      MinValue: 5
      Type: Number

   DatabaseInstanceClass:
      AllowedValues:
        - db.t2.micro
        - db.t2.medium
        - db.t2.large
        - db.t2.xlarge  
        - db.t2.2xlarge
        - db.t3.large
        - db.t3.xlarge
        - db.t3.2xlarge
        - db.m5.large
        - db.m5.xlarge
      ConstraintDescription: Select valid database instance type
      Default: db.t2.xlarge 
      Description: The database instance type
      Type: String

   MultiAZDatabase:
      AllowedValues:
        - true
        - false
      ConstraintDescription: Must be either true or false
      Default: true
      Description: Creates a Multi-AZ RDS instance
      Type: String

Resources:
   DatabaseSubnetGroup:
     Type: AWS::RDS::DBSubnetGroup
     Properties:
       DBSubnetGroupDescription: Subnet group for the RDS Database
       SubnetIds: 
         - Fn::ImportValue: !Sub ${ExportVpcStackName}-PrivateDBSubnetA
         - Fn::ImportValue: !Sub ${ExportVpcStackName}-PrivateDBSubnetB
       Tags:
         - Key: Name
           Value: Prod Database subnets

   DatabaseInstance:
     Type: AWS::RDS::DBInstance
     Properties:
       AllocatedStorage: !Ref DatabaseAllocatedStorage
       #AvailabilityZone: us-west-2b #!Select [ 3, !GetAZs '' ]
       BackupRetentionPeriod: !Ref DatabaseAllocatedStorage
       DBInstanceClass: !Ref DatabaseInstanceClass
       DBInstanceIdentifier: !Ref DatabaseInstanceIdentifier
       DBName: !Ref DatabaseName
       DBSubnetGroupName: !Ref DatabaseSubnetGroup
       Engine: MySQL
       EngineVersion: 5.7.31
       MasterUsername: !Ref DatabaseUser
       MasterUserPassword: !Ref DatabasePassword
       MultiAZ: !Ref MultiAZDatabase
       VPCSecurityGroups:
         - Fn::ImportValue: !Sub ${ExportVpcStackName}-ProdDatabaseSecurityGroup